var ReviewConstants = {
  RECEIVE_ALL_REVIEWS: "RECEIVE_ALL_REVIEWS",
  RECEIVE_NEW_REVIEW: "RECEIVE_NEW_REVIEW",
  UPDATE_REVIEW: "UPDATE_REVIEW",
  DELETE_REVIEW: "DELETE_REVIEW"
};

module.exports = ReviewConstants;
